### ISSUE TITLE
Client Side Config

### ISSUE THREAD

**Issue by SampsonCrowley** [Sawtaytoes/Ghadyani-Framework-Webpack-React-Redux#2]
what's the right way to collect a client side config into react with this setup? e.g. if I needed to know the server port in the client side.

server/configs seems to only have webpack configs and server side configs

**Comment by Sawtaytoes** [comment]
You're right! There are a few ways of accomplishing this.

### A Few Ideas

1. Add it to `window` in `render-full-page.js` similar to how initial state is being set:
```jsx
<script dangerouslySetInnerHTML={{__html: `window.__INITIAL_STATE__ = ${JSON.stringify(state)}`}} />
```
2. Use `webpack.DefinePlugin()` only in a Webpack client config:
```js
new webpack.DefinePlugin({ 'process.env.NODE_ENV': JSON.stringify(config.getEnv()) }),
```

**Comment by SampsonCrowley** [comment]
that should be enough to work with
