### ISSUE TITLE
Production doesn't compile ES6 server code

### ISSUE THREAD

**Issue by SampsonCrowley** [Sawtaytoes/Ghadyani-Framework-Webpack-React-Redux#3]
server code with es6 import export syntax works in dev, but gives: 
```
(function (exports, require, module, __filename, __dirname) { import
```
in production

**Comment by SampsonCrowley** [comment]
im on 8.2.1 with the latest node.

I only is a problem with server side code (e.g. in the services folder)

Add es6 coded file to server/services.

import into server-prod

**Comment by SampsonCrowley** [comment]
i just noticed that `server.server-dev.js` has `require('babel-core/register')({ presets: ['latest'] })` at the top, while `server-prod.js` does not

**Comment by Sawtaytoes** [comment]
Ah yes, I don't have any special endpoints that use non-Node.js ES6.

If you want newer ECMAScript in your Node.js, you either have to precompile your endpoints or register Babel like `server-dev`.

**Comment by SampsonCrowley** [comment]
seems like an easy enough fix
